
module.exports = {
    
 urls :[
    // "https://www.hugedomains.com/contact.cfm",   //p
    // "https://twitter.com/Contom/contact.html",   //p //no form
    // "https://www.hireheronow.com/contact",   //p  //multiple forms
    // "https://www.cwood.org/cwood/contact_cwood/",      //p
    // "http://www.itcscorp.net/contactus.html",    //p
    // "https://www.hetlinger.org/contact-us",     //p  //captcha???
    // "https://commoditystaffing.com/#contact",   //p
    // "https://www.hrstaff.net/contact/",     //p //iframe //dropdown is an input tag
    // "https://www.staffingbyse7en.com/",     //p  //form is in footer
    // "https://ilanascaremiami.com/contact-us",    //p // no placeholders or labels //custom captcha
    // "https://www.wastaffingllc.com/contact-us",  //p
    // "https://www.deanstaffingandrecruiting.com/contact",       //captcha
    // "https://help.accessncworks.com/hc/en-us/articles/360019765091-Contact-Information", //p
    // "https://www.careertransitionsllc.com/placement-services/", //p
    // "https://www.laborquicknc.com/?utm_source=rsd&utm_medium=gmb#Contact-Us", //p
    // "http://formularesources.com/#contact",         //p //no placeholder and labels. value used instead of placeholder
    // "https://www.thepattytiptoncompany.com/contact-us", //p
    // "https://www.escstaff.com/contact.html",    //p
    // "https://www.asapstaffing24-7.com/contact-us",  //p
    // "https://hirequest.com/contact-us/",    //P
    // "https://www.wellingtonexecutivesearch.com/contact-us",  //f email is textarea //iframe
    // "https://www.bcsmis.com/contact-us/",   //p
    // "https://workforceatlas.org/contact",   //p
    // "https://www.fgp.com/contact-us/",   //p
    // "https://connexissearch.com/contact/",  //f form takes too long to load //iframe //not solved yet
    // "https://www.isg-staffing.com/contact", //captcha
    // "https://www.gemresourcing.com/contact-us/",    //f because of cookie popup
    // "https://www.abicsl.com/contact-us",    //p //no label or placeholder
    // "https://assuredemploymentstaffing.com/contact", //p
    // "https://www.expresspros.com/CouncilBluffsIA/Contact-Us/Default.aspx",  //p
    // "https://www.springbornstaffing.com/temporary-staffing-companies/",     //p
    // "https://www.taylortechnical.com/contact/", //p
    // "https://copelandstaffingandrecruiting.com/contact-us", //p
    // "https://aggressivehiring.com/contact-us/",     //p
    // "https://www.msfingerlakes.com/contact-us-2/",       //p
    // "https://www.can-amconsultants.com/contact.php", //p
    // "https://thecandoragency.net/contact-us",       //p
    // "https://lehmancr.com/contact/",        //f email not filled in the right field
    // "https://www.davidjosephinc.com/contact/",  //p
    // "https://www.nexgoal.com/recruiting-services-contact/",     //f failing due to conflict in xpath priority
    // "https://ehospitalhire.com/contact-us/",    //p
    // "https://bridgeworkpartners.com/contact-us/",   //p
    // "https://www.faharistaffing.com/contact-us/",   //p
    // "https://www.repucare.com/contact-5",   //p
    // "https://onsitesvs.com/contact-us",     //p
    // "https://getbsquared.com/contact/",     //p
    // "https://ajc.lincoln.ne.gov/contact-us/",   //p
    // "https://www.mystaffinc.com/contact/",     //p      
    // "https://theconnectagency.co/contact",      //f form is not present but it's detected in html
    // "https://eliteresources.net/employers",  //f form is detected but not filled
    // "http://www.premierestaffing.net/Premiere2014/contact.html",        //p
    // "https://www.lighthousehrs.net/contact/contact-us",     //captcha
    // "http://www.kaiserwhitney.com/contact/",        //f message typed in phone field. not making sense
    // "https://www.besttemps.com/contact",        //p
    // "https://www.aheadhr.com/contact-us/",       //f dropdown required and last name is not filling
    // "https://huntsville.snelling.com/contact/",      //f  zip code is required and should match the given US state
    // "https://outsource.net/contact/",   //f no form present but its detected in html
    // "https://www.coadvantage.com/contact-us/",      //p
    // "https://stafftodayinc.com/contact-us.html",     //p
    // "https://staffingspecifix.com/contact-us/",     //captcha
    // "https://www.sebenzasource.com/sebenza/contact",        //p
    // "https://www.promptprioritystaffing.com/contact",       //f other mandatory fields present
    // "https://www.arlingtonva.us/Home/Contact-Arlington",        //p
    // "https://www.pettitstaffing.com/contact",        //p
    // "http://ptalents.com/#formulario_contacto",     //f name not filled
    // "https://www.ahelpinghandstaffing.com/contact",     //captcha
    // "https://www.alpstaffing.com/contact",      //p
    // "https://hr.infoprosol.com/contactus.html",     //f form not filled
    // "https://www.expresspros.com/LongviewWA/Contact/Longview/",     //f radio button mandatory
    // "https://energeostaffing.com/contact-us/",      //captcha
    // "https://www.staffingplusjobs.com/contact/",     //p
    // "https://www.consilio.com/contact/",    //p
    // "https://www.reliantstaffing.com/contact/",  //p
    // "https://www.aramark.com/about-us/enterprise-solutions/dietetic-internship/-us",        //p
    // "https://saleminc.com/contact-us/",     //p
    // "https://talentteam.com/contact-us/",    //captcha
    // "https://x3tradesmen.com/contact-us/",      //captcha
    // "https://www.greencountrystaffing.com/contact/",        //p
    // "https://www.positiveresultsstaffing.com/",     //p
    // "http://allstaffusa.com/contact.php",    //p
    // "https://thejobshoppe.com/contact-us/",     //p
    // "https://www.hamilton-ryker.com/contact/",       //p
    // "https://www.solutionsstaffing.com/contact/",       //p
    // "https://caracollective.org/contact/",       //f form not filled
    // "https://promaxpersonnel.com/contact-us/",       //p
    // "https://www.seekcareers.com/contact-us/",       //captcha
    // "https://arrowworkforce.com/contact-us/",        //captcha
    // "http://www.suntechpros.com/",      //captcha
    // "https://www.ebintl.com/ContactUS",      //f form not filled
    // "https://digipulsetech.com/contact-us/",     //f address is textarea
    // "https://xyant.com/contact-us/",     //f name not filled
    // "https://www.luxoft.com/contact-form",       //captcha
    // "https://www.blackknightinc.com/contact-us/?",       //captcha
    // "http://www.sibitalent.com/contact.php",     //f form not filled
    // "https://sparibis.com/s/contact",        //p
    // "https://infinitysolutions.ca/contact-us/",      //f name not filled
    // "https://creospan.com/contact-us/",      //f name not filled
    // "http://www.vertexsolutionsinc.com/contact.shtml",       //p 
    // "http://www.highbridgeusa.com/contactus.html",       //
    // "http://www.pintegrallc.com/?page_id=17",        //p
    // "http://biz3tech.com/contact/",
    // "https://www.smartsourcetec.com/contact_us",
    // "https://itscient.com/contact-us",
    // "https://www.neweratech.com/us/contact-us/",
    // "https://www.grantpeters.com/contact-grant-peters-associates.html",
    // "https://www.useready.com/contact-us/",
    // "https://www.marathonus.com/contact/",
    // "https://talentiqo.com/contact-us/",
    // "http://www.corevance.com/contact.html",
    // "https://tumblekidswatertown.com/contact/",
    // "https://www.affinity.co/contact-us",
    // "https://www.helloflare.com/copy-of-disability-contact-form",
    // "https://soccershopusa.com/contact/",
    // "https://www.globalcu.org/financial-planning/contact/",
    // "https://www.indstate.edu/contact",
    // "https://www.simplot.com/contact_us",
    // "https://www.sohohouse.com/en-us/contact",
    // "https://familiesusa.org/about/#contact-us",
    // "https://lcsnw.org/about/contact/",
    // "https://www.alto.us/contact/",
    // "https://www.tpicap.com/",
    // "https://www.aaryah.com/pages/contact-us",
    // "https://www.raysearchlabs.com/about/contact/",
    // "https://www.chromaus.com/contact.html",
    // "http://www.anrcomfortcare.com/contact-us.html",
    // "https://www.abm.com/contact/",
    // "https://www.pegasusresidential.com/contact-us",
    // "https://www.jorgeng.com/contact",
    // "https://morganwhite.com/contact",
    // "https://mrscleanpgh.com/contact/",
    // "https://www.simonswerk.com/service/contact",
    // "https://stonemountaintoyota.com/contact-us",
    // "https://www.cheyenneregional.org/contact/",
    // "https://www.paivafinancial.com/contact",
    // "https://sciodpm.com/contact/",
    // "https://mstaxprep.com/contact-us/",
    // "https://www.redpointglobal.com/company/contact/",
    // "https://www.frankhajekandassociates.com/contact.php",
    // "http://www.trif.com/contact-us/",
    // "https://www.m-csi.com/contact-us/",
    // "http://kkdesignonline.com/#contact",
    // "http://www.ncomm.com/ncomm/contact-us",
    // "https://telebright.com/#contact",
    // "https://www.bdkinc.com/contact",
    // "https://healaccounting.com/contact-us/",
    // "https://cyberconnection.us/contact-us/",
    // "https://tannerwest.com/contact-us/",
    // "http://techsolutionsmaine.com/#contact-1",
    // "https://bettystaxservices.com/contact",
    // "https://www.bonaventuredesign.com/contact-us/",
    // "https://ginnyweaver.com/contact/",
    // "https://artc.systems/contact-us/",
    // "https://propylon.com/contact/",
    // "https://www.platecompany.com/index.php/contact",
    // "http://nybbleteksolutions.com/contact-us/",
    // "https://www.morrow-accounting.com/contact",
    // "https://fosteraccountingin.com/contact",
    // "https://systemdomaininc.com/contact.php",
    // "https://www.stablepug.com/#contact",
    // "https://www.mstech-eyes.com/contact-us",
    // "https://newcastleassoc.com/contact-chicago-information-technology-staffing/",
    // "https://amsacct.com/contacts",
    // "http://www.dennisrwencel.com/ContactUs.html",
    // "https://infobankmediaseo.com/contact/",
    // "https://www.cashregisterguys.com/contact.html",
    // "https://www.julieawhelancpallc.com/",
    // "http://www.rangeus.com/contact/", //no form
    // "https://helpdesk.bitrix24.com/ticket.php?ID=0",
    // "https://fedeleandassociates.com/#contact",  //iframe
    // "https://emergingbusinessservices.com/contact/", //no form
    // "https://www.sagebooksinc.com/contact", //no form
    // "https://knowink.com/contact-us/",
    // "https://www.innovativetimingsystems.com/contact-us", // no form
    // "http://corptechs.com/contact-us.aspx", //no form
    // "http://hmscpa.com/contact-us/",    //no form
    // "https://mackmediallc.com/#contact-us", //contains custom captcha. nameattr of captcha is quiz
    // "https://triafed.com/contact-us/", 
    // "https://designbratzleadville.com/contact",
    // "https://quantale.io/#contact",                 //pass
    // "http://coswebsiteservices.com/contact.html",       //pass
    // "https://www.sms360.com/",      //company name is textareea  //form in footer
    // "https://www.rydzikcpa.com/contact",
    // "https://www.biginternet.co.uk/contact/", // np form
    // "http://alpineaccountingservices.com/contact/",     //contains question wihtout captcha
    // "https://www.mjpenistoncpa.com/contact-us",         //pass
    // "https://www.feiscocpa.com/contact",            //no form
    // "http://www.moviltrack.com/contacto.html"    //non english site //submut button text is "Eviar" (language is spanish)
    "https://www.cfastaffing.com/contact/",
"https://www.cinqtechstaffing.com/contact",
"https://www.citygospelmission.org/about-us/contact-us/",
"https://www.cloudstaffingpro.com/find-a-job/",
"https://www.cmpersonnel.com/contact/",
"https://www.co-staff.com/#contact-info",
"https://www.coastjobs.com/contact/",
"https://www.cohesionllc.com/contact",
"https://www.communicationscollaborative.com/contact/",
"https://www.compass-sys.com/contact-us/",
"https://www.connectionstrainingandstaffing.com/contact/",
"https://www.contrackstaffingsolutions.com/contact",
"https://www.covelogroup.com/contact/",
"https://www.coworxstaffing.com/about/contact-us/",
"https://www.cps4jobs.com/contact-us/",
"https://www.craftforce.com/contact-us/",
"https://www.creditrepairnow.com/contact#consultation",
"https://www.cromsource.com/contact/",
"https://www.crownstaffing.com/contact/",
"https://www.cs-recruiting.com/contact-us",
"https://www.csi-executivesearch.com/contact-us/",
"https://www.cumberlandsworkforce.com/contact-us",
"https://www.cwood.org/cwood/contact_cwood/",
"https://www.daleyaa.com/contact/",
"https://www.dansources.com/copy-of-employee-forms",
"https://www.davis-staffing.com/admin-recruitment-agencies/",
"https://www.daviscos.com/professional-recruiting-services/",
"https://www.dccca.org/contact-us/",
"https://www.dentalpower.com/contact",
"https://www.deployhr.com/contact/",
"https://www.digitalprospectors.com/contact",
"https://www.direct-response.co.uk/contact-us/",
"https://www.diversifiedstaffing.com/contact/",
"https://www.diversityjobsourcellc.com/contact",
"https://www.domainmarket.com/contact",
"https://www.dqstaff.com/contact-us/",
"https://www.dsijobs.net/contact-us/",
"https://www.durhamstaffingsolutions.com/contact-us/4839452",
"https://www.dwinc.org/contact/",
"https://www.dynamicrecruiting.com/contact-us",
"https://www.easternhires.com/contact",
"https://www.easternindianaworks.org/contactjs",
"https://www.easternmillwrights.com/Module/MailForms/Contact/default",
"https://www.eesforjobs.com/contact/",
"https://www.ekcep.org/contact-us",
"https://www.elitepersonnel.com/contact-2",
"https://www.elitestaffinginc.com/contact.php",
"https://www.emergeprofessional.com/contact-us/",
"https://www.emploiquebec.gouv.qc.ca/en/contact-us/",
"https://www.employeeloyaltyoptimization.com/#contactus",
"https://www.employmentstl.org/contact",
"https://www.employpg.org/contact-us/",
"https://www.engineeringsearchgroup.com/contact/",
"https://www.envision.com/employment-agencies-st-louis-phoenix/",
"https://www.episervice.org/who-we-are/contact-us/",
"https://www.ericcpc.com/contact-us",
"https://www.ermsclaims.net/contact",
"https://www.escstaff.com/contact.html",
"https://www.esrstaffing.com/contact",
"https://www.essentialpersonnel.com/contact/",
"https://www.excelstaff.com/employment-contact-us",
"https://www.expert-staffing.com/contact-us/",
"https://www.expresspros.com/ActonMA/Contact-Us/Default.aspx",
"https://www.expresspros.com/ActonMASRG/Contact-Us/Default.aspx",
"https://www.expresspros.com/AndersonMuncieIN/Contact-Us/Default.aspx",
"https://www.expresspros.com/BloomingtonIL/Contact-Us/Default.aspx",
"https://www.expresspros.com/BloomingtonIN/Contact-Us/Default.aspx",
"https://www.expresspros.com/BrowardCountySouthFL/Contact-Us/Default.aspx",
"https://www.expresspros.com/CarbondaleIL/Contact-Us/Default.aspx",
"https://www.expresspros.com/CarolStreamIL/Contact-Us/Default.aspx",
"https://www.expresspros.com/ChampaignIL/Contact-Us/Default.aspx",
"https://www.expresspros.com/ChelseaMA/Contact-Us/Default.aspx",
"https://www.expresspros.com/ChicagoNW/Contact-Us/Default.aspx",
"https://www.expresspros.com/CoeurdAleneID/Contact-Us/Default.aspx",
"https://www.expresspros.com/ColumbiaMD/Contact-Us/Default.aspx",
"https://www.expresspros.com/DanvilleIL/Contact-Us/Default.aspx",
"https://www.expresspros.com/DeKalbIL/Contact-Us/Default.aspx",
"https://www.expresspros.com/DubuqueIASRG/Contact-Us/Default.aspx",
"https://www.expresspros.com/EdwardsvilleIL/Contact-Us/Default.aspx",
"https://www.expresspros.com/ElkhartIN/Contact-Us/Default.aspx",
"https://www.expresspros.com/FairviewHeightsIL/Contact-Us/Default.aspx",
"https://www.expresspros.com/GreencastlePA/Contact-Us/Default.aspx",
"https://www.expresspros.com/HarrodsburgKY/Contact-Us/Default.aspx",
"https://www.expresspros.com/IndyEast/Contact-Us/Default.aspx",
"https://www.expresspros.com/IndySouth/Contact-Us/Default.aspx",
"https://www.expresspros.com/JoplinMO/Contact-Us/Default.aspx",
"https://www.expresspros.com/KankakeeIL/Contact-Us/Default.aspx",
"https://www.expresspros.com/LafayetteIN/Contact-Us/Default.aspx",
"https://www.expresspros.com/LewistonID/Contact-Us/Default.aspx",
"https://www.expresspros.com/LibertyvilleIL/Contact-Us/Default.aspx",
"https://www.expresspros.com/LombardIL/Contact-Us/Default.aspx",
"https://www.expresspros.com/MarylandHeights/Contact-Us/Default.aspx",
"https://www.expresspros.com/MattoonIL/Contact-Us/Refer-A-Friend.aspx",
"https://www.expresspros.com/MetairieLA/Contact-Us/Default.aspx",
"https://www.expresspros.com/MTVernon/Contact-Us/Default.aspx",
"https://www.expresspros.com/NapervilleIL/Contact-Us/Default.aspx",
"https://www.expresspros.com/NewOrleansLA/Contact-Us/Default.aspx",
"https://www.expresspros.com/NewtonMA/Contact-Us/Default.aspx",
"https://www.expresspros.com/NorthAuroraIL/Contact-Us/Default.aspx",
"https://www.expresspros.com/NorthbrookIL/Contact-Us/Default.aspx",
"https://www.expresspros.com/NorthlandKCMO/Contact-Us/Default.aspx",
"https://www.expresspros.com/NWCincinnatiOH/Contact-Us/Default.aspx",
"https://www.expresspros.com/OakLawnIL/Contact-Us/Default.aspx",
"https://www.expresspros.com/OmahaNorthDowntownNE/Contact-Us/Default.aspx",
"https://www.expresspros.com/OmahaSouth/Contact-Us/Default.aspx",
"https://www.expresspros.com/OttawaIL/Contact-Us/Default.aspx",
"https://www.expresspros.com/PittsburgKS/Contact-Us/Default.aspx",
"https://www.expresspros.com/RockfordIL/Contact-Us/Default.aspx",
"https://www.expresspros.com/SouthBendIN/Contact-Us/Default.aspx",
"https://www.expresspros.com/SSaintLouisMO/Contact-Us/Default.aspx",
"https://www.expresspros.com/TylerTX/Contact-Us/Default.aspx",
"https://www.expresspros.com/ValparaisoINSRG/Contact-Us/Default.aspx",
"https://www.expresspros.com/VancouverWA/Contact-Us/Default.aspx",
"https://www.expresspros.com/WalthamFraminghamMA/Contact-Us/Default.aspx",
"https://www.expresspros.com/WaukeganIL/Contact-Us/Default.aspx",
"https://www.expresspros.com/Website-Contact.aspx",
"https://www.expresspros.com/WOmahaNE/Contact-Us/Default.aspx",
"https://www.extendedlaborinc.com/",
"https://www.fa-search.com/hire-us",
"https://www.fanning-boston.com/contactus/",
"https://www.findtherightclick.com/contact/",
"https://www.finishlinestaffing.com/contact-us/",
"https://www.firstclassworkforce.com/contact-us/",
"https://www.firststepstaffing.com/contact",
"https://www.flexicorps.com/contact-2-2",
"https://www.flextechs.com/contact/",
"https://www.flynnlsg.com/contact",
"https://www.fmtalent.com/contact-fm-talent",
"https://www.foodmanagementsearch.com/contact-us/",
"https://www.foodstaff.com/contact/",
"https://www.freedomstaffing.us/contact/",
"https://www.fulllife.com/contact/",
"https://www.g2securestaff.com/contact/",
"https://www.geainc.com/contact-us/",
"https://www.genesis10.com/locations",
"https://www.getmedstaffing.com/contact",
"https://www.giftedhealthcare.com/contact-us/",
"https://www.gkstaff.com/direct-hire-staffing/",
"https://www.globalconsultingmd.com/contact",
"https://www.globalprofessionalsvs.com/contact-us/",
"https://www.goodwill.org/contact-us/",
"https://www.goodwinrecruiting.com/contact-us",
"https://www.gotoworkone.com/contactus",
"https://www.gpworkplace.ca/contact/",
"https://www.greenkeyllc.com/about-us/#form-contact-us-anchor",
"https://www.grimeslegal.com/contact",
"https://www.gruensearch.com/contact",
"https://www.guardianhealthstaff.com/contact-us",
"https://www.hagmansearch.com/contact-us",
"https://www.hallmarkpersonnelinc.com/contact",
"https://www.halpinservices.com/contact-us/",
"https://www.hamilton-ryker.com/contact/",
"https://www.hamiltonconnection.com/contact-jobs-staffing-agency/",
"https://www.happycandidates.com/hc_contact.php",
"https://www.hctravelnursing.com/contact",
"https://www.heartofthehouse.com/contact",
"https://www.hereshelp.com/contact-us/",
"https://www.herrinpolicedepartment.com/contactus",
"https://www.hetlinger.org/contact-us",
"https://www.highprofilestaffing.com/temp-agencies/",
"https://www.hirepartnership.com/staffing-specialists-boston/",
"https://www.horizonpacificstaffing.com/contact",
"https://www.horizontaltalent.com/contact-us",
"https://www.hrdinc.com/contact",
"https://www.hrhlabor.com/contact-us",
"https://www.hss.com/abird-apex/contact-us",
"https://www.hugedomains.com/contact.cfm",
"https://www.hutcoinc.com/contact-us/",
"https://www.idr-inc.com/contact-us/",
"https://www.iescorp.net/contact/",
"https://www.industrialtradeservices.com/contact-us/",
"https://www.infinity-staff.com/contact.html",
"https://www.insearchrecruiting.com/contact-us/",
"https://www.integratedstaffing.ca/contact-us",
"https://www.interstatestaffing.com/contact",
"https://www.iseecareers.com/contact",
"https://www.itsjobs.ca/contact-us/",
"https://www.ivcc.edu/contactus/",
"https://www.jedwardstaffing.com/contact-us",
"https://www.jhstaffing.com/temp-to-hire-job-opportunities/contact-a-recruiter/",
"https://www.jmjtalent.com/contact/",
"https://www.jmorrissey.com/contact-us/",
"https://www.jmtstaffingsolutions.com/contact",
"https://www.job-seekers.co.uk/contact-us/",
"https://www.jobboarddoctor.com/contact/",
"https://www.jobg8.com/ContactUs.aspx",
"https://www.jobletics.com/contact",
"https://www.jobs.ca/contact-us/",
"https://www.jobsight.org/contact-us",
"https://www.jobsintheus.com/contact",
"https://www.jobsquadclaremore.com/",
"https://www.jobsquadhudson.com/copy-of-contact",
"https://www.jovie.com/contact-us/",
"https://www.jvtadvisors.com/contact/",
"https://www.ka-recruiting.com/contact-healthcare-staffing/",
"https://www.kbwfinancial.com/contact/",
"https://www.kcjanitorial.net/contact/",
"https://www.keihin-na.com/contact/",
"https://www.keypersonnel.com/contact-and-map.html",
"https://www.keys.ca/contact/contact.php",
"https://www.kforce.com/contact-us/",
"https://www.kmsstaffing.com/contact",
"https://www.knft.com/contact/",
"https://www.labor-solutions.com/contactus?linktype=JobSeekerHeader",
"https://www.laborfinders.com/contact-us/",
"https://www.labormax.net/ContactUs",
"https://www.laboronsite.com/contact-new-client/",
"https://www.lakeshoretalent.com/contact/",
"https://www.launchtws.com/contact/",
"https://www.lawresources.com/contact",
"https://www.leadsservices.com/contact-us",
"https://www.leonstaffingdc.com/contact-8",
"https://www.lgsstaffing.com/contact-us/",
"https://www.lifestylestaffing.com/contact-us",
"https://www.lmbassociates.com/contacts/",
"https://www.lmcareerconsultants2.com/contact-us",
"https://www.locumlife.org/Contact",
"https://www.lowershoreajc.org/contact-us/",
"https://www.lrostaffing.com/contact/",
"https://www.luttrellstaffing.com/contact/",
"https://www.lynxinc.com/contact/",
"https://www.mainestaff.com/contact-us/",
"https://www.maineworks.us/contact",
"https://www.malonehc.com/contact-us/",
"https://www.marathonstaffing.com/employers/#Contactus",
"https://www.marathonstaffing.com/locations/#Contactus",
"https://www.masmedicalstaffing.com/contact-us/",
"https://www.mass.gov/orgs/masshire-department-of-career-services",
"https://www.masshirefhcareers.org/contact-us/",
"https://www.massilvaconsulting.com/contact",
"https://www.mastersonstaffing.com/job-seekers/contact/",
"https://www.matthewsemploys.com/labor-industrial-clerical-employment/",
"https://www.maximhealthcare.com/contact-maxim-healthcare/",
"https://www.maximstaffing.com/contact-maxim-staffing/",
"https://www.mclabor.com/contact-us/",
"https://www.medcepts.com/contact/",
"https://www.medicalsolutions.com/contact/",
"https://www.medservicesnow.com/contact/",
"https://www.medwinhcs.com/contact/",
"https://www.memstaff.com/contact",
"https://www.meritogroup.com/contact-us/",
"https://www.metinc.org/contact",
"https://www.milwaukeestaffing.com/contact",
"https://www.mjmorgangroup.com/contact/",
"https://www.mmstaffingagency.com/contact",
"https://www.monumentstaffing.net/contact-us/",
"https://www.msistaff.com/contact",
"https://www.mwsstl.com/contact",
"https://www.mycareersalary.com/contact-us/",
"https://www.myemployeeconnections.com/contact.html",
"https://www.myshiftapp.com/contact",
"https://www.mystaffinc.com/contact/",
"https://www.naglergroup.com/contact/",
"https://www.nasrecruitment.com/contact-nas/",
"https://www.nebaworks.com/contact.html",
"https://www.nejobs.net/contact-us",
"https://www.nesc.com/contact-us/",
"https://www.nextaff.com/contact-us-new/",
"https://www.njschooljobs.com/contact",
"https://www.nri-staffing.com/job-recruiters/",
"https://www.obrienco.com/Software-Sales-Recruiting-Contact-Us-Glen-Ellyn-IL.html",
"https://www.ofe.ca/contact",
"https://www.officetimesavers.net/contact.htm",
"https://www.omj-cinham.org/contact-us/",
"https://www.omjlawrencecounty.org/contact/",
"https://www.one2verify.com/contact",
"https://www.oneilstaffingsolutions.com/",
"https://www.oningroup.com/contact/",
"https://www.onlinewritingjobs.com/contact-us/",
"https://www.onsitepersonnel.com/contact",
"https://www.ontimehr.ca/contact/index.html",
"https://www.ontimestaffing.com/contact-us",
"https://www.otaservice.net/",
"https://www.overachieversstaffing.com/order-staff-contact-us/",
"https://www.p3-recruiting.com/contact",
"https://www.pace-staffing.com/contact/",
"https://www.pacestaffingllc.com/contact-us/",
"https://www.paragonitpros.com/contact",
"https://www.parallelemployment.com/contact/",
"https://www.partnerspersonnel.com/contact-us",
"https://www.patriceandassociates.com/contact-us/",
"https://www.payrollservicesllconline.com/contact",
"https://www.pegstaff.com/contact-us/",
"https://www.penmac.com/contact/",
"https://www.people-first.co.uk/contact",
"https://www.peoplelinkgroup.com/contact/",
"https://www.peopleshareworks.com/contact-us/",
"https://www.peppershock.com/contact-2/",
"https://www.phase3clinical.com/contact-us/",
"https://www.phidd.org/#contact",
"https://www.phoenixstaffing.net/contact",
"https://www.physicianrecruiting.com/contact-us/",
"https://www.pivotalsolutions.com/contact/",
"https://www.placementmates.com/contact-us/",
"https://www.portlandnannies.com/contacts/",
"https://www.power-it.net/contact",
"https://www.premierstaffing.com/contact/",
"https://www.premierstaffing.org/contact-premier-staffing/",
"https://www.premierstaffingkc.com/contact-us",
"https://www.premierstaffingsolutions.net/contact",
"https://www.premierstaffingsource.com/contact-us",
"https://www.pridestaff.com/contact-us/",
"https://www.primary-staffing.net/contact-us/",
"https://www.prnhealthservices.com/contact-us",
"https://www.procurepersonnel.com/contact/",
"https://www.prodrivers.com/contact/",
"https://www.progresshealthcarestaffing.org/?segment=contact",
"https://www.prologistix.com/contact/",
"https://www.proresources.com/light-industrial-temp-agencies-contact-us/",
"https://www.prosearchmaine.com/about/contact-us/",
"https://www.prosourceinc.com/contact-us",
"https://www.prstgevents.com/contact",
"https://www.psandr.com/contact/",
"https://www.psstaffing.com/contact-us/",
"https://www.pushforce.net/contact",
"https://www.q-staffing.com/contact-us/",
"https://www.qmstaffing.com/contact-us/",
"https://www.qsnurses.com/contact-us/",
"https://www.qualitymindsets.com/contact",
"https://www.queencg.com/contact",
"https://www.quicdent.com/contact-us",
"https://www.r-wgroup.com/contact-us",
"https://www.rcsearchgroup.com/contact-us",
"https://www.redcapstaffing.com/contact/",
"https://www.regaldomesticsinc.com/contact-us",
"https://www.remedystaffing.com/contact/",
"https://www.resource-connection.com/contact-us/",
"https://www.resourcemfg.com/contact/",
"https://www.resourceoptions.com/contact-us",
"https://www.retailcareersforme.com/contact",
"https://www.roberthalf.com/contact-us",
"https://www.robertsjoseph.com/contact-us.html",
"https://www.rockislandcountyil.gov/Directory.aspx",
"https://www.ryzen.com/contact-us/",
"https://www.sandyou.ca/contact/",
"https://www.saveddllc.com/contact-us/",
"https://www.savvystaffing.com/contact",
"https://www.schultestaffing.com/contact-us/",
"https://www.sebenzasource.com/sebenza/contact",
"https://www.sedonastaffing.com/contact-us",
"https://www.seekcareers.com/contact-us/",
"https://www.seekprofessionals.com/contact-us/",
"https://www.select.com/contact/",
"https://www.selectionresources.com/contact-us/",
"https://www.servicespecialistltd.com/contact-us/",
"https://www.servihospitality.com/",
"https://www.sgcstaffing.com/contactus",
"https://www.shortstaffedusa.com/contact-us",
"https://www.sinbrand.com/contact-us/",
"https://www.slsinc.com/contact-us",
"https://www.sndstaffing.com/contact",
"https://www.snelling.com/contacts/",
"https://www.snellingstl.com/contact-us/",
"https://www.snicompanies.com/staffing-recruiting/",
"https://www.socialworkprn.com/contact-us",
"https://www.softworldinc.com/contract-staffing-services-contact-us/",
"https://www.soinworks.com/contact",
"https://www.southernmedicalstaffing.com/contact-us",
"https://www.southsix.com/contact",
"https://www.specializedstaffing.com/contact-us/",
"https://www.spectrumhcs.com/contact-us/",
"https://www.speedway.com/about/contact",
"https://www.spherion.com/contact-us/",
"https://www.springbornstaffing.com/temporary-staffing-companies/",
"https://www.ssemploymentpartners.com/",
"https://www.ssslabor.com/contact-us.html",
"https://www.staffedinc.com/contact",
"https://www.staffersinc.com/temporary-office-employment/",
"https://www.stafflinkusa.com/contact-us/",
"https://www.staffoneltd.com/contact-us/",
"https://www.staffquickjobs.com/contact-bloomington-il",
"https://www.staffsolutions.com/contact-us/",
"https://www.staffsourceusa.com/contact-us/",
"https://www.staffworksmke.com/contact/",
"https://www.starleasing.com/contact-us/",
"https://www.stlouis-mo.gov/government/contact.cfm",
"https://www.stlouis-mo.gov/government/departments/slate/#orgContact",
"https://www.strategicrecruitmentsolutions.com/about-us/contact/",
"https://www.strategicstaff.com/locations/",
"https://www.stridestaffing.com/light-industrial-staffing/",
"https://www.summersetinc.com/contact-us/",
"https://www.sunflowercareers.com/contact.html",
"https://www.sunvalley.com/contact-info",
"https://www.superior-staffing.com/contact-us/",
"https://www.supremestaffingia.com/contact",
"https://www.sustained-quality.com/contact-us/",
"https://www.swaneventsstaffing.com/contact",
"https://www.syncreon.com/contact/",
"https://www.synergiesystems.com/contact-us/",
"https://www.szantoncompany.com/contact-5",
"https://www.talentmanagementprofessionals.com/about-us.html#ContactUs",
"https://www.talgroup.net/contact-us/",
"https://www.taskeforce.com/contact-us/",
"https://www.taskimpetusinc.com/contact/",
"https://www.tdm-assoc.com/contact",
"https://www.tdsb.on.ca/Contact-Us",
"https://www.technicalresources.co.uk/cm/contact",
"https://www.teksystems.com/en/contact-us",
"https://www.thecareerstrategygroup.com/contact-us/",
"https://www.thefrankgrp.com/west-chicago-staffing-agencies/",
"https://www.thejobguide.com/contact-us",
"https://www.thelasallenetwork.com/contact-us/",
"https://www.thelibertygroup.com/contact/",
"https://www.themhgrp.com/contact-us/",
"https://www.themindfinders.com/employment-agencies-dc/",
"https://www.thepalmergroup.com/contact",
"https://www.thepanthergrp.com/contact-us/",
"https://www.theplanetforward.com/contact-us/",
"https://www.thetrakgroup.com/contact-staffing-specialists/",
"https://www.thevesumegroup.com/contact-us/",
"https://www.theworkforceconnection.org/contact-us/",
"https://www.timewisestaffing.com/contact",
"https://www.titanmed.com/contact/",
"https://www.tkoconstructionservices.com/contact-us",
"https://www.tkostaffing.com/contact-us",
"https://www.tlcindustrial.com/employment-agency-kentucky/",
"https://www.tmsservices.com/technical/contact",
"https://www.tntpersonnel.com/contact-us/refer-a-friend/",
"https://www.total-employment.co.uk/contact-us/",
"https://www.totalitystaffing.com/contact/",
"https://www.totalnursesnetwork-iowa.com/contact/",
"https://www.tra-inc.org/contactus",
"https://www.tradesmeninternational.com/contact/",
"https://www.triad-eng.com/contact/",
"https://www.trinitynursingstaffllc.com/contact-us",
"https://www.tripleepartners.com/contact",
"https://www.triunelogistics.net/#contact",
"https://www.trnstaffing.com/contact-us/",
"https://www.trrcopo.org/contact-us/",
"https://www.trucadence.com/blank-3",
"https://www.turningpointboston.com/about-contact-us/",
"https://www.udac.org/contact/",
"https://www.umstaffing.com/contact",
"https://www.unltdstaff.com/contact-us",
"https://www.uptownstaffing.com/contact-us/",
"https://www.usacs.com/contact",
"https://www.vectorsolutions.com/contact-us/",
"https://www.ver-fiedstaffing.com/contact/",
"https://www.vermilioncountyworks.org/contact/",
"https://www.verticalstaffingresources.com/contact-us/",
"https://www.vip-staffing.com/contact",
"https://www.vipemployment.net/contact-9",
"https://www.vitalnursingagencyllc.com/contact",
"https://www.vocationalresourcesmaine.com/contact",
"https://www.volt.com/contact",
"https://www.vp-staffing.com/location-and-contact-staffing",
"https://www.wapitimedical.com/healthcare-temp-agency/",
"https://www.westaff.com/contact/",
"https://www.westportone.com/contact/",
"https://www.westsidepersonnel.com/general-labor-staffing/",
"https://www.wicaa.org/contact/",
"https://www.wickedstaffingsolutions.com/contact-us/",
"https://www.williamsonemployment.com/st-joseph-office/",
"https://www.willsourcestaffing.com/contact/",
"https://www.wilmarkgroup.com/index.php/contact-us/",
"https://www.wisestaffinggroup.com/contact-us/",
"https://www.wittkieffer.com/contact-us/",
"https://www.wiverse.com/contact/",
"https://www.wocinc.org/contact",
"https://www.woodstaffing.com/manufacturing-recruitment-agencies/",
"https://www.work4manpower.com/contact-us.html",
"https://www.workcr.com/",
"https://www.workingsolutionsusa.com/contact-us/",
"https://www.worksourcestaff.com/contact-worksource-central-southeastern-des-moines-temp-employment-agencies/",
"https://www.wvregion2.org/contact/contact-form/",
"https://www.zdaya.com/contact-zda-supply-chain-recruiting/",
"https://xclusivestaffing.com/contact-us/",
"https://xtraeffort.com/contact/",
"https://yesstaffingllc.com/contact/",
"https://yupro.com/#contact",
"https://zingrecruiting.com/contact-us/",

    
    

]};
